
/* Drop Tables */

DROP TABLE OA_LEAVE;
DROP TABLE OA_NOTIFY_RECORD;
DROP TABLE OA_NOTIFY;
DROP TABLE OA_NOTIFY_DEP;
DROP TABLE OA_TEST_AUDIT;




/* Create Tables */

CREATE TABLE OA_LEAVE
(
	ID VARCHAR2(64) NOT NULL,
	PROCESS_INSTANCE_ID VARCHAR2(64),
	START_TIME TIMESTAMP,
	END_TIME TIMESTAMP,
	LEAVE_TYPE VARCHAR2(20),
	REASON NVARCHAR2(255),
	APPLY_TIME TIMESTAMP,
	REALITY_START_TIME TIMESTAMP,
	REALITY_END_TIME TIMESTAMP,
	CREATE_BY VARCHAR2(64) NOT NULL,
	CREATE_DATE TIMESTAMP NOT NULL,
	UPDATE_BY VARCHAR2(64) NOT NULL,
	UPDATE_DATE TIMESTAMP NOT NULL,
	REMARKS NVARCHAR2(255),
	DEL_FLAG CHAR(1) DEFAULT '0' NOT NULL,
	PRIMARY KEY (ID)
);


CREATE TABLE OA_NOTIFY
(
	ID VARCHAR2(64) NOT NULL,
	TYPE CHAR(1),
	TITLE NVARCHAR2(200),
	CONTENT NVARCHAR2(2000),
	FILES NVARCHAR2(2000),
	STATUS CHAR(1),
	CREATE_BY VARCHAR2(64) NOT NULL,
	CREATE_DATE TIMESTAMP NOT NULL,
	UPDATE_BY VARCHAR2(64) NOT NULL,
	UPDATE_DATE TIMESTAMP NOT NULL,
	REMARKS NVARCHAR2(255),
	DEL_FLAG CHAR(1) DEFAULT '0' NOT NULL,
	FILE_NAME VARCHAR2(3000),
	NOTIFY_SCOPE VARCHAR2(1) DEFAULT '0' NOT NULL,
	PRIMARY KEY (ID)
);


CREATE TABLE OA_NOTIFY_DEP
(
	ID VARCHAR2(64) NOT NULL,
	DEP_ID VARCHAR2(64) NOT NULL,
	READ_FLAG VARCHAR2(1) DEFAULT '0' NOT NULL,
	READ_DATE DATE,
	NOTIFY_ID VARCHAR2(64) NOT NULL,
	DEL_FLAG VARCHAR2(1) DEFAULT '0' NOT NULL,
	PRIMARY KEY (ID)
);


CREATE TABLE OA_NOTIFY_RECORD
(
	ID VARCHAR2(64) NOT NULL,
	OA_NOTIFY_ID VARCHAR2(64),
	USER_ID VARCHAR2(64),
	READ_FLAG CHAR(1) DEFAULT '0',
	READ_DATE DATE,
	PRIMARY KEY (ID)
);


CREATE TABLE OA_TEST_AUDIT
(
	ID VARCHAR2(64) NOT NULL,
	PROC_INS_ID VARCHAR2(64),
	USER_ID VARCHAR2(64),
	OFFICE_ID VARCHAR2(64),
	POST NVARCHAR2(255),
	AGE CHAR(1),
	EDU NVARCHAR2(255),
	CONTENT NVARCHAR2(255),
	OLDA VARCHAR2(255),
	OLDB VARCHAR2(255),
	OLDC VARCHAR2(255),
	NEWA VARCHAR2(255),
	NEWB VARCHAR2(255),
	NEWC VARCHAR2(255),
	ADD_NUM VARCHAR2(255),
	EXE_DATE VARCHAR2(255),
	HR_TEXT NVARCHAR2(255),
	LEAD_TEXT NVARCHAR2(255),
	MAIN_LEAD_TEXT NVARCHAR2(255),
	CREATE_BY VARCHAR2(64) NOT NULL,
	CREATE_DATE TIMESTAMP NOT NULL,
	UPDATE_BY VARCHAR2(64) NOT NULL,
	UPDATE_DATE TIMESTAMP NOT NULL,
	REMARKS NVARCHAR2(255),
	DEL_FLAG CHAR(1) DEFAULT '0' NOT NULL,
	CONSTRAINT SYS_C0016476 PRIMARY KEY (ID)
);



/* Create Indexes */

CREATE INDEX OA_LEAVE_CREATE_BY ON OA_LEAVE (CREATE_BY);
CREATE INDEX OA_LEAVE_PROCESS_INSTANCE_ID ON OA_LEAVE (PROCESS_INSTANCE_ID);
CREATE INDEX OA_LEAVE_DEL_FLAG ON OA_LEAVE (DEL_FLAG);
CREATE INDEX OA_NOTIFY_DEL_FLAG ON OA_NOTIFY (DEL_FLAG);
CREATE INDEX OA_NOTIFY_RECORD_NOTIFY_ID ON OA_NOTIFY_RECORD (OA_NOTIFY_ID);
CREATE INDEX OA_NOTIFY_RECORD_USER_ID ON OA_NOTIFY_RECORD (USER_ID);
CREATE INDEX OA_NOTIFY_RECORD_READ_FLAG ON OA_NOTIFY_RECORD (READ_FLAG);
CREATE INDEX OA_TEST_AUDIT_DEL_FLAG ON OA_TEST_AUDIT (DEL_FLAG);



/* Comments */

COMMENT ON TABLE OA_LEAVE IS '请假流程表';
COMMENT ON COLUMN OA_LEAVE.ID IS '编号';
COMMENT ON COLUMN OA_LEAVE.PROCESS_INSTANCE_ID IS '流程实例编号';
COMMENT ON COLUMN OA_LEAVE.START_TIME IS '开始时间';
COMMENT ON COLUMN OA_LEAVE.END_TIME IS '结束时间';
COMMENT ON COLUMN OA_LEAVE.LEAVE_TYPE IS '请假类型';
COMMENT ON COLUMN OA_LEAVE.REASON IS '请假理由';
COMMENT ON COLUMN OA_LEAVE.APPLY_TIME IS '申请时间';
COMMENT ON COLUMN OA_LEAVE.REALITY_START_TIME IS '实际开始时间';
COMMENT ON COLUMN OA_LEAVE.REALITY_END_TIME IS '实际结束时间';
COMMENT ON COLUMN OA_LEAVE.CREATE_BY IS '创建者';
COMMENT ON COLUMN OA_LEAVE.CREATE_DATE IS '创建时间';
COMMENT ON COLUMN OA_LEAVE.UPDATE_BY IS '更新者';
COMMENT ON COLUMN OA_LEAVE.UPDATE_DATE IS '更新时间';
COMMENT ON COLUMN OA_LEAVE.REMARKS IS '备注信息';
COMMENT ON COLUMN OA_LEAVE.DEL_FLAG IS '删除标记';
COMMENT ON TABLE OA_NOTIFY IS '通知通告';
COMMENT ON COLUMN OA_NOTIFY.ID IS '编号';
COMMENT ON COLUMN OA_NOTIFY.TYPE IS '类型';
COMMENT ON COLUMN OA_NOTIFY.TITLE IS '标题';
COMMENT ON COLUMN OA_NOTIFY.CONTENT IS '内容';
COMMENT ON COLUMN OA_NOTIFY.FILES IS '附件';
COMMENT ON COLUMN OA_NOTIFY.STATUS IS '状态';
COMMENT ON COLUMN OA_NOTIFY.CREATE_BY IS '创建者';
COMMENT ON COLUMN OA_NOTIFY.CREATE_DATE IS '创建时间';
COMMENT ON COLUMN OA_NOTIFY.UPDATE_BY IS '更新者';
COMMENT ON COLUMN OA_NOTIFY.UPDATE_DATE IS '更新时间';
COMMENT ON COLUMN OA_NOTIFY.REMARKS IS '备注信息';
COMMENT ON COLUMN OA_NOTIFY.DEL_FLAG IS '删除标记';
COMMENT ON COLUMN OA_NOTIFY.FILE_NAME IS '附件名称';
COMMENT ON COLUMN OA_NOTIFY.NOTIFY_SCOPE IS '发布范围';
COMMENT ON TABLE OA_NOTIFY_DEP IS '部门公告记录';
COMMENT ON COLUMN OA_NOTIFY_DEP.ID IS '编号';
COMMENT ON COLUMN OA_NOTIFY_DEP.DEP_ID IS '部门ID';
COMMENT ON COLUMN OA_NOTIFY_DEP.READ_FLAG IS '阅读标记';
COMMENT ON COLUMN OA_NOTIFY_DEP.READ_DATE IS '阅读时间';
COMMENT ON COLUMN OA_NOTIFY_DEP.NOTIFY_ID IS '公告ID';
COMMENT ON COLUMN OA_NOTIFY_DEP.DEL_FLAG IS '删除标记';
COMMENT ON TABLE OA_NOTIFY_RECORD IS '通知通告发送记录';
COMMENT ON COLUMN OA_NOTIFY_RECORD.ID IS '编号';
COMMENT ON COLUMN OA_NOTIFY_RECORD.OA_NOTIFY_ID IS '通知通告ID';
COMMENT ON COLUMN OA_NOTIFY_RECORD.USER_ID IS '接受人';
COMMENT ON COLUMN OA_NOTIFY_RECORD.READ_FLAG IS '阅读标记';
COMMENT ON COLUMN OA_NOTIFY_RECORD.READ_DATE IS '阅读时间';
COMMENT ON TABLE OA_TEST_AUDIT IS '审批流程测试表';
COMMENT ON COLUMN OA_TEST_AUDIT.ID IS '编号';
COMMENT ON COLUMN OA_TEST_AUDIT.PROC_INS_ID IS '流程实例ID';
COMMENT ON COLUMN OA_TEST_AUDIT.USER_ID IS '变动用户';
COMMENT ON COLUMN OA_TEST_AUDIT.OFFICE_ID IS '归属部门';
COMMENT ON COLUMN OA_TEST_AUDIT.POST IS '岗位';
COMMENT ON COLUMN OA_TEST_AUDIT.AGE IS '性别';
COMMENT ON COLUMN OA_TEST_AUDIT.EDU IS '学历';
COMMENT ON COLUMN OA_TEST_AUDIT.CONTENT IS '调整原因';
COMMENT ON COLUMN OA_TEST_AUDIT.OLDA IS '现行标准 薪酬档级';
COMMENT ON COLUMN OA_TEST_AUDIT.OLDB IS '现行标准 月工资额';
COMMENT ON COLUMN OA_TEST_AUDIT.OLDC IS '现行标准 年薪总额';
COMMENT ON COLUMN OA_TEST_AUDIT.NEWA IS '调整后标准 薪酬档级';
COMMENT ON COLUMN OA_TEST_AUDIT.NEWB IS '调整后标准 月工资额';
COMMENT ON COLUMN OA_TEST_AUDIT.NEWC IS '调整后标准 年薪总额';
COMMENT ON COLUMN OA_TEST_AUDIT.ADD_NUM IS '月增资';
COMMENT ON COLUMN OA_TEST_AUDIT.EXE_DATE IS '执行时间';
COMMENT ON COLUMN OA_TEST_AUDIT.HR_TEXT IS '人力资源部门意见';
COMMENT ON COLUMN OA_TEST_AUDIT.LEAD_TEXT IS '分管领导意见';
COMMENT ON COLUMN OA_TEST_AUDIT.MAIN_LEAD_TEXT IS '集团主要领导意见';
COMMENT ON COLUMN OA_TEST_AUDIT.CREATE_BY IS '创建者';
COMMENT ON COLUMN OA_TEST_AUDIT.CREATE_DATE IS '创建时间';
COMMENT ON COLUMN OA_TEST_AUDIT.UPDATE_BY IS '更新者';
COMMENT ON COLUMN OA_TEST_AUDIT.UPDATE_DATE IS '更新时间';
COMMENT ON COLUMN OA_TEST_AUDIT.REMARKS IS '备注信息';
COMMENT ON COLUMN OA_TEST_AUDIT.DEL_FLAG IS '删除标记';



