
/* Drop Tables */

DROP TABLE FILE_HISTORY;
DROP TABLE FILE_RELEASED;
DROP TABLE MAIL_RECEIVE;
DROP TABLE MAIL_SEND;
DROP TABLE MSG_EMAIL;
DROP TABLE MSG_INTERNAL;
DROP TABLE MSG_REMIND;
DROP TABLE NEWS_HISTORY;
DROP TABLE WS_FILES;
DROP TABLE WS_NEWS;
DROP TABLE WS_POST;




/* Create Tables */

-- 文件下载记录
CREATE TABLE FILE_HISTORY
(
	-- 主键
	ID VARCHAR2(64) NOT NULL,
	-- 下载文件主键
	FILE_ID VARCHAR2(64) NOT NULL,
	-- 下载者
	FILE_DOWNLOAD VARCHAR2(64) NOT NULL,
	-- 下载文件名
	FILE_NAME VARCHAR2(2100),
	-- 创建者
	CREATE_BY VARCHAR2(64) NOT NULL,
	-- 创建时间
	CREATE_DATE TIMESTAMP NOT NULL,
	-- 更新者
	UPDATE_BY VARCHAR2(64) NOT NULL,
	-- 更新时间
	UPDATE_DATE TIMESTAMP NOT NULL,
	-- 删除标记,0：正常，1：删除
	DEL_FLAG CHAR(1) DEFAULT '0' NOT NULL,
	-- 备注
	REMARKS VARCHAR2(900),
	PRIMARY KEY (ID)
);


-- 文件发布范围
CREATE TABLE FILE_RELEASED
(
	-- 主键
	ID VARCHAR2(64) NOT NULL,
	-- 文件主键
	FILE_ID VARCHAR2(64) NOT NULL,
	-- 文件共享人，文件查看权，单个人共享
	FILE_SHARE VARCHAR2(64),
	-- 文件授权者，共享文件的人（文件拥有人）
	FILE_GRANTEE VARCHAR2(64) NOT NULL,
	-- 文件下载权，是否拥有文件下载权，0：有，1：无
	FILE_DOWNLOAD CHAR(1) DEFAULT '0' NOT NULL,
	-- 文件修改权，0：有，1：无
	FILE_EDIT CHAR(1) DEFAULT '1' NOT NULL,
	-- 共享文件到部门
	FILE_DEP VARCHAR2(64),
	-- 创建者
	CREATE_BY VARCHAR2(64) NOT NULL,
	-- 创建时间
	CREATE_DATE TIMESTAMP NOT NULL,
	-- 更新者
	UPDATE_BY VARCHAR2(64) NOT NULL,
	-- 更新时间
	UPDATE_DATE TIMESTAMP NOT NULL,
	-- 删除标记,0：正常，1：删除
	DEL_FLAG CHAR(1) DEFAULT '0' NOT NULL,
	-- 备注
	REMARKS VARCHAR2(900),
	PRIMARY KEY (ID)
);


-- 邮件接收者信息
CREATE TABLE MAIL_RECEIVE
(
	-- 主键
	ID VARCHAR2(64) NOT NULL,
	-- 邮件接收者
	MAIL_RECEIVE VARCHAR2(64) NOT NULL,
	-- 邮件主键
	MAIL_ID VARCHAR2(64) NOT NULL,
	-- 发送者主键
	MAIL_SENDER VARCHAR2(64) NOT NULL,
	-- 阅读状态,0:未读，1：已读
	MAIL_STATE VARCHAR2(1) DEFAULT '0' NOT NULL,
	-- 阅读时间
	READ_DATE DATE,
	-- 删除标记,0:正常，1：删除
	IS_DEL CHAR(1) DEFAULT '0' NOT NULL,
	PRIMARY KEY (ID)
);


-- 邮件发送信息
CREATE TABLE MAIL_SEND
(
	-- 主键
	ID VARCHAR2(64) NOT NULL,
	-- 邮件主键
	MAIL_ID VARCHAR2(64) NOT NULL,
	-- 发送者ID
	SEND_ID VARCHAR2(64) NOT NULL,
	-- 是否删除，0：正常，1：删除
	IS_DEL CHAR(1) DEFAULT '0' NOT NULL,
	-- 发送时间
	SEND_DATE DATE NOT NULL,
	-- 创建者
	CREATE_BY VARCHAR2(64) NOT NULL,
	-- 创建时间
	CREATE_DATE TIMESTAMP NOT NULL,
	-- 更新者
	UPDATE_BY VARCHAR2(64) NOT NULL,
	-- 更新时间
	UPDATE_DATE TIMESTAMP NOT NULL,
	-- 删除标记,0：正常，1：删除
	DEL_FLAG CHAR(1) DEFAULT '0' NOT NULL,
	-- 备注
	REMARKS VARCHAR2(900),
	PRIMARY KEY (ID)
);


-- 内部邮件
CREATE TABLE MSG_EMAIL
(
	-- 主键
	ID VARCHAR2(64) NOT NULL,
	-- 邮件接收者,多个接收者中间用‘,’分割
	MAIL_ACCEPTOR VARCHAR2(6000) NOT NULL,
	-- 接收者姓名
	ACCEPTOR_NAMES VARCHAR2(4000) NOT NULL,
	-- 邮件标题
	MAIL_TITLE VARCHAR2(300) NOT NULL,
	-- 邮件内容
	MAIL_CONTENT CLOB NOT NULL,
	-- 文件名称
	FILE_NAMES VARCHAR2(6000),
	-- 附件路径
	FILE_PATH VARCHAR2(6000),
	-- 是否提醒,0:提醒，1：不提醒
	IS_REMIND CHAR(1) DEFAULT '1' NOT NULL,
	-- 是否发送,0:发送，1：草稿，2：撤回
	IS_SEND CHAR(1) DEFAULT '1' NOT NULL,
	-- 发送时间
	SEND_DATE DATE,
	-- 存稿时间
	DRAFT_DATE DATE NOT NULL,
	-- 是否删除,0:正常，1：删除
	IS_DEL CHAR(1) DEFAULT '0' NOT NULL,
	-- 创建者
	CREATE_BY VARCHAR2(64) NOT NULL,
	-- 创建时间
	CREATE_DATE TIMESTAMP NOT NULL,
	-- 更新者
	UPDATE_BY VARCHAR2(64) NOT NULL,
	-- 更新时间
	UPDATE_DATE TIMESTAMP NOT NULL,
	-- 删除标记,0：正常，1：删除
	DEL_FLAG CHAR(1) DEFAULT '0' NOT NULL,
	-- 备注
	REMARKS VARCHAR2(900),
	PRIMARY KEY (ID)
);


-- 内部消息
CREATE TABLE MSG_INTERNAL
(
	-- 主键
	ID VARCHAR2(64) NOT NULL,
	-- 收信人
	ACCEPTOR VARCHAR2(6400) NOT NULL,
	-- 消息内容
	MSG_CONTENT VARCHAR2(3000) NOT NULL,
	-- 阅读状态，0：未读，1：已读
	MSG_READ CHAR(1) DEFAULT '0' NOT NULL,
	-- 阅读时间
	READ_DATE DATE,
	-- 创建者
	CREATE_BY VARCHAR2(64) NOT NULL,
	-- 创建时间
	CREATE_DATE TIMESTAMP NOT NULL,
	-- 更新者
	UPDATE_BY VARCHAR2(64) NOT NULL,
	-- 更新时间
	UPDATE_DATE TIMESTAMP NOT NULL,
	-- 删除标记,0：正常，1：删除
	DEL_FLAG CHAR(1) DEFAULT '0' NOT NULL,
	-- 备注
	REMARKS VARCHAR2(900),
	PRIMARY KEY (ID)
);


-- 消息提醒设置
CREATE TABLE MSG_REMIND
(
	-- 主键
	ID VARCHAR2(64) NOT NULL,
	-- 公告提醒，0：提醒，1：不提醒
	REMIND_NOTICE CHAR(1) DEFAULT '1' NOT NULL,
	-- 站内消息提醒，0：提醒，1：不提醒
	REMIND_MSG CHAR(1) DEFAULT '0' NOT NULL,
	-- 创建者
	CREATE_BY VARCHAR2(64) NOT NULL,
	-- 创建时间
	CREATE_DATE TIMESTAMP NOT NULL,
	-- 更新者
	UPDATE_BY VARCHAR2(64) NOT NULL,
	-- 更新时间
	UPDATE_DATE TIMESTAMP NOT NULL,
	-- 删除标记,0：正常，1：删除
	DEL_FLAG CHAR(1) DEFAULT '0' NOT NULL,
	-- 备注
	REMARKS VARCHAR2(900),
	PRIMARY KEY (ID)
);


-- 新闻阅读历史
CREATE TABLE NEWS_HISTORY
(
	-- 主键
	ID VARCHAR2(64) NOT NULL,
	-- 新闻主键
	NEWS_ID VARCHAR2(64) NOT NULL,
	-- 阅读者
	NEWS_READER VARCHAR2(64) NOT NULL,
	-- 阅读时间
	READ_DATE DATE NOT NULL,
	-- 创建者
	CREATE_BY VARCHAR2(64) NOT NULL,
	-- 创建时间
	CREATE_DATE TIMESTAMP NOT NULL,
	-- 更新者
	UPDATE_BY VARCHAR2(64) NOT NULL,
	-- 更新时间
	UPDATE_DATE TIMESTAMP NOT NULL,
	-- 删除标记,0：正常，1：删除
	DEL_FLAG CHAR(1) DEFAULT '0' NOT NULL,
	-- 备注
	REMARKS VARCHAR2(900),
	PRIMARY KEY (ID)
);


-- 文件管理
CREATE TABLE WS_FILES
(
	-- 主键
	ID VARCHAR2(64) NOT NULL,
	-- 文件标题
	FILE_TITLE VARCHAR2(1200) NOT NULL,
	-- 文件
	FILE_NAMES VARCHAR2(2100),
	-- 文件路径
	FILE_PATH VARCHAR2(2100) NOT NULL,
	-- 创建者
	CREATE_BY VARCHAR2(64) NOT NULL,
	-- 创建时间
	CREATE_DATE TIMESTAMP NOT NULL,
	-- 更新者
	UPDATE_BY VARCHAR2(64) NOT NULL,
	-- 更新时间
	UPDATE_DATE TIMESTAMP NOT NULL,
	-- 删除标记,0：正常，1：删除
	DEL_FLAG CHAR(1) DEFAULT '0' NOT NULL,
	-- 备注
	REMARKS VARCHAR2(900),
	PRIMARY KEY (ID)
);


-- 新闻信息
CREATE TABLE WS_NEWS
(
	-- 主键
	ID VARCHAR2(64) NOT NULL,
	-- 新闻标题
	NEWS_TITLE VARCHAR2(300) NOT NULL,
	-- 新闻内容
	NEWS_CONTENT CLOB NOT NULL,
	-- 是否置顶，0：不置顶，1：置顶
	NEWS_TOP CHAR(1) DEFAULT '0',
	-- 排序
	NEWS_SORT NUMBER(10,0) DEFAULT 0,
	-- 创建者
	CREATE_BY VARCHAR2(64) NOT NULL,
	-- 创建时间
	CREATE_DATE TIMESTAMP NOT NULL,
	-- 更新者
	UPDATE_BY VARCHAR2(64) NOT NULL,
	-- 更新时间
	UPDATE_DATE TIMESTAMP NOT NULL,
	-- 删除标记,0：正常，1：删除
	DEL_FLAG CHAR(1) DEFAULT '0' NOT NULL,
	-- 备注
	REMARKS VARCHAR2(900),
	PRIMARY KEY (ID)
);


-- 岗位信息
CREATE TABLE WS_POST
(
	-- 主键
	ID VARCHAR2(64) NOT NULL,
	-- 岗位名称
	POST_NAME VARCHAR2(60) NOT NULL,
	-- 排序
	POST_SORT NUMBER(10,0) NOT NULL,
	-- 是否显示,0:显示，1：不显示
	IS_VIEW CHAR(1) DEFAULT '0' NOT NULL,
	-- 创建者
	CREATE_BY VARCHAR2(64) NOT NULL,
	-- 创建时间
	CREATE_DATE TIMESTAMP NOT NULL,
	-- 更新者
	UPDATE_BY VARCHAR2(64) NOT NULL,
	-- 更新时间
	UPDATE_DATE TIMESTAMP NOT NULL,
	-- 删除标记,0：正常，1：删除
	DEL_FLAG CHAR(1) DEFAULT '0' NOT NULL,
	-- 备注
	REMARKS VARCHAR2(900),
	PRIMARY KEY (ID)
);



/* Comments */

COMMENT ON TABLE FILE_HISTORY IS '文件下载记录';
COMMENT ON COLUMN FILE_HISTORY.ID IS '主键';
COMMENT ON COLUMN FILE_HISTORY.FILE_ID IS '下载文件主键';
COMMENT ON COLUMN FILE_HISTORY.FILE_DOWNLOAD IS '下载者';
COMMENT ON COLUMN FILE_HISTORY.FILE_NAME IS '下载文件名';
COMMENT ON COLUMN FILE_HISTORY.CREATE_BY IS '创建者';
COMMENT ON COLUMN FILE_HISTORY.CREATE_DATE IS '创建时间';
COMMENT ON COLUMN FILE_HISTORY.UPDATE_BY IS '更新者';
COMMENT ON COLUMN FILE_HISTORY.UPDATE_DATE IS '更新时间';
COMMENT ON COLUMN FILE_HISTORY.DEL_FLAG IS '删除标记,0：正常，1：删除';
COMMENT ON COLUMN FILE_HISTORY.REMARKS IS '备注';
COMMENT ON TABLE FILE_RELEASED IS '文件发布范围';
COMMENT ON COLUMN FILE_RELEASED.ID IS '主键';
COMMENT ON COLUMN FILE_RELEASED.FILE_ID IS '文件主键';
COMMENT ON COLUMN FILE_RELEASED.FILE_SHARE IS '文件共享人，文件查看权，单个人共享';
COMMENT ON COLUMN FILE_RELEASED.FILE_GRANTEE IS '文件授权者，共享文件的人（文件拥有人）';
COMMENT ON COLUMN FILE_RELEASED.FILE_DOWNLOAD IS '文件下载权，是否拥有文件下载权，0：有，1：无';
COMMENT ON COLUMN FILE_RELEASED.FILE_EDIT IS '文件修改权，0：有，1：无';
COMMENT ON COLUMN FILE_RELEASED.FILE_DEP IS '共享文件到部门';
COMMENT ON COLUMN FILE_RELEASED.CREATE_BY IS '创建者';
COMMENT ON COLUMN FILE_RELEASED.CREATE_DATE IS '创建时间';
COMMENT ON COLUMN FILE_RELEASED.UPDATE_BY IS '更新者';
COMMENT ON COLUMN FILE_RELEASED.UPDATE_DATE IS '更新时间';
COMMENT ON COLUMN FILE_RELEASED.DEL_FLAG IS '删除标记,0：正常，1：删除';
COMMENT ON COLUMN FILE_RELEASED.REMARKS IS '备注';
COMMENT ON TABLE MAIL_RECEIVE IS '邮件接收者信息';
COMMENT ON COLUMN MAIL_RECEIVE.ID IS '主键';
COMMENT ON COLUMN MAIL_RECEIVE.MAIL_RECEIVE IS '邮件接收者';
COMMENT ON COLUMN MAIL_RECEIVE.MAIL_ID IS '邮件主键';
COMMENT ON COLUMN MAIL_RECEIVE.MAIL_SENDER IS '发送者主键';
COMMENT ON COLUMN MAIL_RECEIVE.MAIL_STATE IS '阅读状态,0:未读，1：已读';
COMMENT ON COLUMN MAIL_RECEIVE.READ_DATE IS '阅读时间';
COMMENT ON COLUMN MAIL_RECEIVE.IS_DEL IS '删除标记,0:正常，1：删除';
COMMENT ON TABLE MAIL_SEND IS '邮件发送信息';
COMMENT ON COLUMN MAIL_SEND.ID IS '主键';
COMMENT ON COLUMN MAIL_SEND.MAIL_ID IS '邮件主键';
COMMENT ON COLUMN MAIL_SEND.SEND_ID IS '发送者ID';
COMMENT ON COLUMN MAIL_SEND.IS_DEL IS '是否删除，0：正常，1：删除';
COMMENT ON COLUMN MAIL_SEND.SEND_DATE IS '发送时间';
COMMENT ON COLUMN MAIL_SEND.CREATE_BY IS '创建者';
COMMENT ON COLUMN MAIL_SEND.CREATE_DATE IS '创建时间';
COMMENT ON COLUMN MAIL_SEND.UPDATE_BY IS '更新者';
COMMENT ON COLUMN MAIL_SEND.UPDATE_DATE IS '更新时间';
COMMENT ON COLUMN MAIL_SEND.DEL_FLAG IS '删除标记,0：正常，1：删除';
COMMENT ON COLUMN MAIL_SEND.REMARKS IS '备注';
COMMENT ON TABLE MSG_EMAIL IS '内部邮件';
COMMENT ON COLUMN MSG_EMAIL.ID IS '主键';
COMMENT ON COLUMN MSG_EMAIL.MAIL_ACCEPTOR IS '邮件接收者,多个接收者中间用‘,’分割';
COMMENT ON COLUMN MSG_EMAIL.ACCEPTOR_NAMES IS '接收者姓名';
COMMENT ON COLUMN MSG_EMAIL.MAIL_TITLE IS '邮件标题';
COMMENT ON COLUMN MSG_EMAIL.MAIL_CONTENT IS '邮件内容';
COMMENT ON COLUMN MSG_EMAIL.FILE_NAMES IS '文件名称';
COMMENT ON COLUMN MSG_EMAIL.FILE_PATH IS '附件路径';
COMMENT ON COLUMN MSG_EMAIL.IS_REMIND IS '是否提醒,0:提醒，1：不提醒';
COMMENT ON COLUMN MSG_EMAIL.IS_SEND IS '是否发送,0:发送，1：草稿，2：撤回';
COMMENT ON COLUMN MSG_EMAIL.SEND_DATE IS '发送时间';
COMMENT ON COLUMN MSG_EMAIL.DRAFT_DATE IS '存稿时间';
COMMENT ON COLUMN MSG_EMAIL.IS_DEL IS '是否删除,0:正常，1：删除';
COMMENT ON COLUMN MSG_EMAIL.CREATE_BY IS '创建者';
COMMENT ON COLUMN MSG_EMAIL.CREATE_DATE IS '创建时间';
COMMENT ON COLUMN MSG_EMAIL.UPDATE_BY IS '更新者';
COMMENT ON COLUMN MSG_EMAIL.UPDATE_DATE IS '更新时间';
COMMENT ON COLUMN MSG_EMAIL.DEL_FLAG IS '删除标记,0：正常，1：删除';
COMMENT ON COLUMN MSG_EMAIL.REMARKS IS '备注';
COMMENT ON TABLE MSG_INTERNAL IS '内部消息';
COMMENT ON COLUMN MSG_INTERNAL.ID IS '主键';
COMMENT ON COLUMN MSG_INTERNAL.ACCEPTOR IS '收信人';
COMMENT ON COLUMN MSG_INTERNAL.MSG_CONTENT IS '消息内容';
COMMENT ON COLUMN MSG_INTERNAL.MSG_READ IS '阅读状态，0：未读，1：已读';
COMMENT ON COLUMN MSG_INTERNAL.READ_DATE IS '阅读时间';
COMMENT ON COLUMN MSG_INTERNAL.CREATE_BY IS '创建者';
COMMENT ON COLUMN MSG_INTERNAL.CREATE_DATE IS '创建时间';
COMMENT ON COLUMN MSG_INTERNAL.UPDATE_BY IS '更新者';
COMMENT ON COLUMN MSG_INTERNAL.UPDATE_DATE IS '更新时间';
COMMENT ON COLUMN MSG_INTERNAL.DEL_FLAG IS '删除标记,0：正常，1：删除';
COMMENT ON COLUMN MSG_INTERNAL.REMARKS IS '备注';
COMMENT ON TABLE MSG_REMIND IS '消息提醒设置';
COMMENT ON COLUMN MSG_REMIND.ID IS '主键';
COMMENT ON COLUMN MSG_REMIND.REMIND_NOTICE IS '公告提醒，0：提醒，1：不提醒';
COMMENT ON COLUMN MSG_REMIND.REMIND_MSG IS '站内消息提醒，0：提醒，1：不提醒';
COMMENT ON COLUMN MSG_REMIND.CREATE_BY IS '创建者';
COMMENT ON COLUMN MSG_REMIND.CREATE_DATE IS '创建时间';
COMMENT ON COLUMN MSG_REMIND.UPDATE_BY IS '更新者';
COMMENT ON COLUMN MSG_REMIND.UPDATE_DATE IS '更新时间';
COMMENT ON COLUMN MSG_REMIND.DEL_FLAG IS '删除标记,0：正常，1：删除';
COMMENT ON COLUMN MSG_REMIND.REMARKS IS '备注';
COMMENT ON TABLE NEWS_HISTORY IS '新闻阅读历史';
COMMENT ON COLUMN NEWS_HISTORY.ID IS '主键';
COMMENT ON COLUMN NEWS_HISTORY.NEWS_ID IS '新闻主键';
COMMENT ON COLUMN NEWS_HISTORY.NEWS_READER IS '阅读者';
COMMENT ON COLUMN NEWS_HISTORY.READ_DATE IS '阅读时间';
COMMENT ON COLUMN NEWS_HISTORY.CREATE_BY IS '创建者';
COMMENT ON COLUMN NEWS_HISTORY.CREATE_DATE IS '创建时间';
COMMENT ON COLUMN NEWS_HISTORY.UPDATE_BY IS '更新者';
COMMENT ON COLUMN NEWS_HISTORY.UPDATE_DATE IS '更新时间';
COMMENT ON COLUMN NEWS_HISTORY.DEL_FLAG IS '删除标记,0：正常，1：删除';
COMMENT ON COLUMN NEWS_HISTORY.REMARKS IS '备注';
COMMENT ON TABLE WS_FILES IS '文件管理';
COMMENT ON COLUMN WS_FILES.ID IS '主键';
COMMENT ON COLUMN WS_FILES.FILE_TITLE IS '文件标题';
COMMENT ON COLUMN WS_FILES.FILE_NAMES IS '文件';
COMMENT ON COLUMN WS_FILES.FILE_PATH IS '文件路径';
COMMENT ON COLUMN WS_FILES.CREATE_BY IS '创建者';
COMMENT ON COLUMN WS_FILES.CREATE_DATE IS '创建时间';
COMMENT ON COLUMN WS_FILES.UPDATE_BY IS '更新者';
COMMENT ON COLUMN WS_FILES.UPDATE_DATE IS '更新时间';
COMMENT ON COLUMN WS_FILES.DEL_FLAG IS '删除标记,0：正常，1：删除';
COMMENT ON COLUMN WS_FILES.REMARKS IS '备注';
COMMENT ON TABLE WS_NEWS IS '新闻信息';
COMMENT ON COLUMN WS_NEWS.ID IS '主键';
COMMENT ON COLUMN WS_NEWS.NEWS_TITLE IS '新闻标题';
COMMENT ON COLUMN WS_NEWS.NEWS_CONTENT IS '新闻内容';
COMMENT ON COLUMN WS_NEWS.NEWS_TOP IS '是否置顶，0：不置顶，1：置顶';
COMMENT ON COLUMN WS_NEWS.NEWS_SORT IS '排序';
COMMENT ON COLUMN WS_NEWS.CREATE_BY IS '创建者';
COMMENT ON COLUMN WS_NEWS.CREATE_DATE IS '创建时间';
COMMENT ON COLUMN WS_NEWS.UPDATE_BY IS '更新者';
COMMENT ON COLUMN WS_NEWS.UPDATE_DATE IS '更新时间';
COMMENT ON COLUMN WS_NEWS.DEL_FLAG IS '删除标记,0：正常，1：删除';
COMMENT ON COLUMN WS_NEWS.REMARKS IS '备注';
COMMENT ON TABLE WS_POST IS '岗位信息';
COMMENT ON COLUMN WS_POST.ID IS '主键';
COMMENT ON COLUMN WS_POST.POST_NAME IS '岗位名称';
COMMENT ON COLUMN WS_POST.POST_SORT IS '排序';
COMMENT ON COLUMN WS_POST.IS_VIEW IS '是否显示,0:显示，1：不显示';
COMMENT ON COLUMN WS_POST.CREATE_BY IS '创建者';
COMMENT ON COLUMN WS_POST.CREATE_DATE IS '创建时间';
COMMENT ON COLUMN WS_POST.UPDATE_BY IS '更新者';
COMMENT ON COLUMN WS_POST.UPDATE_DATE IS '更新时间';
COMMENT ON COLUMN WS_POST.DEL_FLAG IS '删除标记,0：正常，1：删除';
COMMENT ON COLUMN WS_POST.REMARKS IS '备注';



